# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Bootcamp_Test_Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ["self-hosted"]  

    steps:
    - uses: actions/checkout@v4
    
    - name: Allow PowerShell scripts in this job
      shell: pwsh
      run: |
         Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
         Get-ExecutionPolicy -List

     
    - name: Add dotnet to PATH
      shell: pwsh
      run: |
         echo "DOTNET_ROOT=$env:DOTNET_INSTALL_DIR" >> $env:GITHUB_ENV
         echo "$env:DOTNET_INSTALL_DIR" >> $env:GITHUB_PATH
         dotnet --info

    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: BootCamp_API/BootCamp_API
    
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: BootCamp_API/BootCamp_API
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: BootCamp_API/BootCamp_API
    