# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Bootcamp_Test_Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: BootCamp_API/BootCamp_API
    
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: BootCamp_API/BootCamp_API
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: BootCamp_API/BootCamp_API
    